
import { BibEntry, Gender } from "./types";

export const SAMPLE_TUTORIAL_SCRIPT = [
    {
        title: "Welcome to the Portuguese-Chinese Translation Lab",
        content: "This sample set is based on actual archival records of Portuguese literature in China. Observe how specific cities like Haikou or Nanning became strategic nodes for certain genres."
    },
    {
        title: "Translator Networks: The Human Factor",
        content: "Switch to 'Network' view. You can see how veteran translators like Fan Weixin or Yao Jingming connect different publishing houses across decades."
    },
    {
        title: "Spatial Flow: From Portugal to the East",
        content: "In 'GIS Lab', the lines represent the journey from Lisbon (Source) to various Chinese cities. Use 'Density' to see where production intensity is highest."
    }
];

export const COORDS: Record<string, [number, number]> = {
    "portugal": [-9.1393, 38.7223], "葡萄牙": [-9.1393, 38.7223],
    "lisbon": [-9.1393, 38.7223], "里斯本": [-9.1393, 38.7223],
    "beijing": [116.4074, 39.9042], "北京": [116.4074, 39.9042],
    "shanghai": [121.4737, 31.2304], "上海": [121.4737, 31.2304],
    "macau": [113.5439, 22.1987], "澳门": [113.5439, 22.1987],
    "hong kong": [114.1733, 22.3193], "香港": [114.1733, 22.3193],
    "taipei": [121.5654, 25.0330], "台北": [121.5654, 25.0330],
    "haikou": [110.3312, 20.0319], "海口": [110.3312, 20.0319],
    "nanjing": [118.7969, 32.0603], "南京": [118.7969, 32.0603],
    "shijiazhuang": [114.5025, 38.0455], "石家庄": [114.5025, 38.0455],
    "wuhan": [114.3054, 30.5931], "武汉": [114.3054, 30.5931],
    "changsha": [112.9388, 28.2280], "长沙": [112.9388, 28.2280],
    "nanning": [108.3200, 22.8240], "南宁": [108.3200, 22.8240],
    "hangzhou": [120.1535, 30.2874], "杭州": [120.1535, 30.2874],
    "chongqing": [106.5507, 29.5630], "重庆": [106.5507, 29.5630],
    "jinan": [117.0009, 36.6758], "济南": [117.0009, 36.6758],
    "tianjin": [117.2008, 39.1257], "天津": [117.2008, 39.1257],
    "changchun": [125.3245, 43.8868], "长春": [125.3245, 43.8868],
};

const PT = "Portugal";
const PT_COORD = COORDS["portugal"];

export const SAMPLE_ENTRIES: BibEntry[] = [
    // 2000-2001: The Hainan/Macau Era
    { id: "v2-1", title: "A Capital (大都)", publicationYear: 2000, author: { name: "Eça de Queirós", gender: Gender.MALE }, translator: { name: "Chen Yongyi", gender: Gender.MALE }, publisher: "Hainan / sanhuan Publishing House", city: "Haikou", originalCity: PT, sourceLanguage: "Portuguese", targetLanguage: "Chinese", customMetadata: { sourceCoord: PT_COORD, targetCoord: COORDS["haikou"] } },
    { id: "v2-2", title: "A Capital (大都)", publicationYear: 2000, author: { name: "Eça de Queirós", gender: Gender.MALE }, translator: { name: "Chen Yongyi", gender: Gender.MALE }, publisher: "Instituto Cultural de Macau", city: "Macau", originalCity: PT, sourceLanguage: "Portuguese", targetLanguage: "Chinese", customMetadata: { sourceCoord: PT_COORD, targetCoord: COORDS["macau"] } },
    { id: "v2-3", title: "Barranco de Cegos (盲人之谷)", publicationYear: 2000, author: { name: "António Alves redol", gender: Gender.MALE }, translator: { name: "Sun Chengao", gender: Gender.MALE }, publisher: "Hainan / sanhuan Publishing House", city: "Haikou", originalCity: PT, sourceLanguage: "Portuguese", targetLanguage: "Chinese", customMetadata: { sourceCoord: PT_COORD, targetCoord: COORDS["haikou"] } },
    { id: "v2-4", title: "Barranco de Cegos (盲人之谷)", publicationYear: 2000, author: { name: "António Alves redol", gender: Gender.MALE }, translator: { name: "Sun Chengao", gender: Gender.MALE }, publisher: "Instituto Cultural de Macau", city: "Macau", originalCity: PT, sourceLanguage: "Portuguese", targetLanguage: "Chinese", customMetadata: { sourceCoord: PT_COORD, targetCoord: COORDS["macau"] } },
    { id: "v2-5", title: "Fronteira e outros Contos", publicationYear: 2000, author: { name: "Miguel Torga", gender: Gender.MALE }, translator: { name: "Fan Weixin, Wei Ling", gender: Gender.MALE }, publisher: "Hainan / sanhuan Publishing House", city: "Haikou", originalCity: PT, sourceLanguage: "Portuguese", targetLanguage: "Chinese", customMetadata: { sourceCoord: PT_COORD, targetCoord: COORDS["haikou"] } },
    { id: "v2-6", title: "Fronteira e outros Contos", publicationYear: 2000, author: { name: "Miguel Torga", gender: Gender.MALE }, translator: { name: "Fan Weixin, Wei Ling", gender: Gender.MALE }, publisher: "Instituto Cultural de Macau", city: "Macau", originalCity: PT, sourceLanguage: "Portuguese", targetLanguage: "Chinese", customMetadata: { sourceCoord: PT_COORD, targetCoord: COORDS["macau"] } },
    { id: "v2-7", title: "Amor de Perdição (败德之爱)", publicationYear: 2001, author: { name: "Camilo Castelo Branco", gender: Gender.MALE }, translator: { name: "Wang Suoying", gender: Gender.FEMALE }, publisher: "Hainan / sanhuan Publishing House", city: "Haikou", originalCity: PT, sourceLanguage: "Portuguese", targetLanguage: "Chinese", customMetadata: { sourceCoord: PT_COORD, targetCoord: COORDS["haikou"] } },
    { id: "v2-8", title: "Amor de Perdição (败德之爱)", publicationYear: 2001, author: { name: "Camilo Castelo Branco", gender: Gender.MALE }, translator: { name: "Wang Suoying", gender: Gender.FEMALE }, publisher: "Instituto Cultural de Macau", city: "Macau", originalCity: PT, sourceLanguage: "Portuguese", targetLanguage: "Chinese", customMetadata: { sourceCoord: PT_COORD, targetCoord: COORDS["macau"] } },
    { id: "v2-9", title: "livro do Desassossego", publicationYear: 2001, author: { name: "Fernando Pessoa", gender: Gender.MALE }, translator: { name: "Han Shaogong", gender: Gender.MALE }, publisher: "Reading Times", city: "Taipei", originalCity: PT, sourceLanguage: "Portuguese", targetLanguage: "Chinese", customMetadata: { sourceCoord: PT_COORD, targetCoord: COORDS["taipei"] } },
    
    // Classic Novels
    { id: "v2-10", title: "os Maias (玛雅一家)", publicationYear: 2001, author: { name: "Eça de Queirós", gender: Gender.MALE }, translator: { name: "Zhang Baosheng, Ren Jisheng", gender: Gender.MALE }, publisher: "People's literature Publishing House", city: "Beijing", originalCity: PT, sourceLanguage: "Portuguese", targetLanguage: "Chinese", customMetadata: { sourceCoord: PT_COORD, targetCoord: COORDS["beijing"] } },
    { id: "v2-11", title: "Pequeno Caderno do oriente", publicationYear: 2002, author: { name: "Eugénio de Andrade", gender: Gender.MALE }, translator: { name: "Yao Jingming", gender: Gender.MALE }, publisher: "Instituto Cultural de Macau", city: "Macau", originalCity: PT, sourceLanguage: "Portuguese", targetLanguage: "Chinese", customMetadata: { sourceCoord: PT_COORD, targetCoord: COORDS["macau"] } },
    
    // Saramago Wave
    { id: "v2-12", title: "Ensaio sobre a Cegueira", publicationYear: 2002, author: { name: "José Saramago", gender: Gender.MALE }, translator: { name: "Fan Weixin", gender: Gender.MALE }, publisher: "Hainan Publishing House", city: "Haikou", originalCity: PT, sourceLanguage: "Portuguese", targetLanguage: "Chinese", customMetadata: { sourceCoord: PT_COORD, targetCoord: COORDS["haikou"] } },
    { id: "v2-13", title: "Ensaio sobre a Cegueira", publicationYear: 2002, author: { name: "José Saramago", gender: Gender.MALE }, translator: { name: "Fan Weixin", gender: Gender.MALE }, publisher: "Instituto Cultural de Macau", city: "Macau", originalCity: PT, sourceLanguage: "Portuguese", targetLanguage: "Chinese", customMetadata: { sourceCoord: PT_COORD, targetCoord: COORDS["macau"] } },
    { id: "v2-14", title: "Ensaio sobre a Cegueira", publicationYear: 2002, author: { name: "José Saramago", gender: Gender.MALE }, translator: { name: "Peng Lingxian", gender: Gender.FEMALE }, publisher: "Reading Times", city: "Taipei", originalCity: PT, sourceLanguage: "Portuguese", targetLanguage: "Chinese", customMetadata: { sourceCoord: PT_COORD, targetCoord: COORDS["taipei"] } },
    { id: "v2-15", title: "A lua de Joana", publicationYear: 2003, author: { name: "Maria Gonzalez", gender: Gender.FEMALE }, translator: { name: "Wu Jun", gender: Gender.MALE }, publisher: "Zhonghua Book Company", city: "Beijing", originalCity: PT, sourceLanguage: "Portuguese", targetLanguage: "Chinese", customMetadata: { sourceCoord: PT_COORD, targetCoord: COORDS["beijing"] } },

    // Middle Era (2004-2013)
    { id: "v2-16", title: "Fernando António Nogueira Pessoa", publicationYear: 2004, author: { name: "Fernando Pessoa", gender: Gender.MALE }, translator: { name: "Yang Zi", gender: Gender.MALE }, publisher: "Hebei Education Press", city: "Shijiazhuang", originalCity: PT, sourceLanguage: "Portuguese", targetLanguage: "Chinese", customMetadata: { sourceCoord: PT_COORD, targetCoord: COORDS["shijiazhuang"] } },
    { id: "v2-17", title: "os olhos de Ana Marta", publicationYear: 2004, author: { name: "Alice Vieira", gender: Gender.FEMALE }, translator: { name: "Tan Yanping, Sheng Zhiyin", gender: Gender.FEMALE }, publisher: "Yilin Publishing House", city: "Nanjing", originalCity: PT, sourceLanguage: "Portuguese", targetLanguage: "Chinese", customMetadata: { sourceCoord: PT_COORD, targetCoord: COORDS["nanjing"] } },
    { id: "v2-18", title: "livro do Desassossego", publicationYear: 2004, author: { name: "Fernando Pessoa", gender: Gender.MALE }, translator: { name: "Chen Shi", gender: Gender.MALE }, publisher: "Hunan literature and Art Publishing House", city: "Changsha", originalCity: PT, sourceLanguage: "Portuguese", targetLanguage: "Chinese", customMetadata: { sourceCoord: PT_COORD, targetCoord: COORDS["changsha"] } },
    { id: "v2-19", title: "o Último Papa", publicationYear: 2010, author: { name: "Luís Miguel Rocha", gender: Gender.MALE }, translator: { name: "Huang Yuanyuan", gender: Gender.FEMALE }, publisher: "Changjiang river literature Book Concern", city: "Wuhan", originalCity: PT, sourceLanguage: "Portuguese", targetLanguage: "Chinese", customMetadata: { sourceCoord: PT_COORD, targetCoord: COORDS["wuhan"] } },
    { id: "v2-20", title: "Memorial do Convento", publicationYear: 2011, author: { name: "José Saramago", gender: Gender.MALE }, translator: { name: "Shi Kuanke", gender: Gender.MALE }, publisher: "Reading Times", city: "Taipei", originalCity: PT, sourceLanguage: "Portuguese", targetLanguage: "Chinese", customMetadata: { sourceCoord: PT_COORD, targetCoord: COORDS["taipei"] } },
    { id: "v2-21", title: "Branco no Branco", publicationYear: 2012, author: { name: "Eugénio de Andrade", gender: Gender.MALE }, translator: { name: "Yao Jingming", gender: Gender.MALE }, publisher: "Livros do Meio", city: "Macau", originalCity: PT, sourceLanguage: "Portuguese", targetLanguage: "Chinese", customMetadata: { sourceCoord: PT_COORD, targetCoord: COORDS["macau"] } },
    { id: "v2-22", title: "o Caderno", publicationYear: 2012, author: { name: "José Saramago", gender: Gender.MALE }, translator: { name: "Liao Yanbo", gender: Gender.MALE }, publisher: "Reading Times", city: "Taipei", originalCity: PT, sourceLanguage: "Portuguese", targetLanguage: "Chinese", customMetadata: { sourceCoord: PT_COORD, targetCoord: COORDS["taipei"] } },
    { id: "v2-23", title: "Décadas da ásia", publicationYear: 2013, author: { name: "João de Barros", gender: Gender.MALE }, translator: { name: "He Gaoji", gender: Gender.MALE }, publisher: "Zhonghua Book Company", city: "Beijing", originalCity: PT, sourceLanguage: "Portuguese", targetLanguage: "Chinese", customMetadata: { sourceCoord: PT_COORD, targetCoord: COORDS["beijing"] } },
    { id: "v2-24", title: "Poemas e Ensaios de Alberto Caeiro", publicationYear: 2013, author: { name: "Fernando Pessoa", gender: Gender.MALE }, translator: { name: "Min Xuefei", gender: Gender.FEMALE }, publisher: "Commercial Press", city: "Beijing", originalCity: PT, sourceLanguage: "Portuguese", targetLanguage: "Chinese", customMetadata: { sourceCoord: PT_COORD, targetCoord: COORDS["beijing"] } },
    { id: "v2-25", title: "um Pouco Maior do que o universo Inteiro", publicationYear: 2013, author: { name: "Fernando Pessoa", gender: Gender.MALE }, translator: { name: "Wei Bai", gender: Gender.MALE }, publisher: "Shanghai People's Press", city: "Shanghai", originalCity: PT, sourceLanguage: "Portuguese", targetLanguage: "Chinese", customMetadata: { sourceCoord: PT_COORD, targetCoord: COORDS["shanghai"] } },
    { id: "v2-26", title: "o Homem Duplicado", publicationYear: 2013, author: { name: "José Saramago", gender: Gender.MALE }, translator: { name: "Huang Qian", gender: Gender.FEMALE }, publisher: "Writers Publishing House", city: "Beijing", originalCity: PT, sourceLanguage: "Portuguese", targetLanguage: "Chinese", customMetadata: { sourceCoord: PT_COORD, targetCoord: COORDS["beijing"] } },

    // 2014-2015 Expansion
    { id: "v2-27", title: "A Ilha", publicationYear: 2014, author: { name: "João Gomes de Abreu", gender: Gender.MALE }, translator: { name: "Yang Lei", gender: Gender.MALE }, publisher: "Guangxi Education Press", city: "Nanning", originalCity: PT, sourceLanguage: "Portuguese", targetLanguage: "Chinese", customMetadata: { sourceCoord: PT_COORD, targetCoord: COORDS["nanning"] } },
    { id: "v2-28", title: "viver em Pleno vento", publicationYear: 2014, author: { name: "Sophia de Mello Breyner", gender: Gender.FEMALE }, translator: { name: "Yao Jingming", gender: Gender.MALE }, publisher: "Camões - ICM", city: "Macau", originalCity: PT, sourceLanguage: "Portuguese", targetLanguage: "Chinese", customMetadata: { sourceCoord: PT_COORD, targetCoord: COORDS["macau"] } },
    { id: "v2-29", title: "100 sonetos", publicationYear: 2014, author: { name: "Luís vaz de Camões", gender: Gender.MALE }, translator: { name: "Zhang Weimin", gender: Gender.MALE }, publisher: "Instituto Cultural de Macau", city: "Macau", originalCity: PT, sourceLanguage: "Portuguese", targetLanguage: "Chinese", customMetadata: { sourceCoord: PT_COORD, targetCoord: COORDS["macau"] } },
    { id: "v2-30", title: "Coração de Mãe", publicationYear: 2014, author: { name: "Isabel Minhós Martins", gender: Gender.FEMALE }, translator: { name: "Yang Lei", gender: Gender.MALE }, publisher: "Guangxi Education Press", city: "Nanning", originalCity: PT, sourceLanguage: "Portuguese", targetLanguage: "Chinese", customMetadata: { sourceCoord: PT_COORD, targetCoord: COORDS["nanning"] } },
    { id: "v2-31", title: "Ir e vir", publicationYear: 2014, author: { name: "Isabel Minhós Martins", gender: Gender.FEMALE }, translator: { name: "Yang Lei", gender: Gender.MALE }, publisher: "Guangxi Education Press", city: "Nanning", originalCity: PT, sourceLanguage: "Portuguese", targetLanguage: "Chinese", customMetadata: { sourceCoord: PT_COORD, targetCoord: COORDS["nanning"] } },
    { id: "v2-32", title: "o Mandarim", publicationYear: 2014, author: { name: "Eça de Queirós", gender: Gender.MALE }, translator: { name: "Zhou Hanjun", gender: Gender.MALE }, publisher: "People's literature Publishing House", city: "Beijing", originalCity: PT, sourceLanguage: "Portuguese", targetLanguage: "Chinese", customMetadata: { sourceCoord: PT_COORD, targetCoord: COORDS["beijing"] } },
    { id: "v2-33", title: "Ensaio sobre a Cegueira", publicationYear: 2014, author: { name: "José Saramago", gender: Gender.MALE }, translator: { name: "Fan Weixin", gender: Gender.MALE }, publisher: "Nanhai Publishing Company", city: "Haikou", originalCity: PT, sourceLanguage: "Portuguese", targetLanguage: "Chinese", customMetadata: { sourceCoord: PT_COORD, targetCoord: COORDS["haikou"] } },
    { id: "v2-34", title: "Ensaio sobre a lucidez", publicationYear: 2014, author: { name: "José Saramago", gender: Gender.MALE }, translator: { name: "Fan Weixin", gender: Gender.MALE }, publisher: "Nanhai Publishing Company", city: "Haikou", originalCity: PT, sourceLanguage: "Portuguese", targetLanguage: "Chinese", customMetadata: { sourceCoord: PT_COORD, targetCoord: COORDS["haikou"] } },
    { id: "v2-35", title: "Todos os Nomes", publicationYear: 2014, author: { name: "José Saramago", gender: Gender.MALE }, translator: { name: "Wang Yuan", gender: Gender.FEMALE }, publisher: "Writers Publishing House", city: "Beijing", originalCity: PT, sourceLanguage: "Portuguese", targetLanguage: "Chinese", customMetadata: { sourceCoord: PT_COORD, targetCoord: COORDS["beijing"] } },
    { id: "v2-36", title: "Quando Eu For grande", publicationYear: 2014, author: { name: "Maria Inês Almeida", gender: Gender.FEMALE }, translator: { name: "Wu Xun", gender: Gender.MALE }, publisher: "Jilin Fine Arts Publishing House", city: "Changchun", originalCity: PT, sourceLanguage: "Portuguese", targetLanguage: "Chinese", customMetadata: { sourceCoord: PT_COORD, targetCoord: COORDS["changchun"] } },
    { id: "v2-37", title: "scotoma", publicationYear: 2015, author: { name: "Fernando Pinto do Amaral", gender: Gender.MALE }, translator: { name: "Yao Jingming", gender: Gender.MALE }, publisher: "Chinese university of Hong Kong Press", city: "Hong Kong", originalCity: PT, sourceLanguage: "Portuguese", targetLanguage: "Chinese", customMetadata: { sourceCoord: PT_COORD, targetCoord: COORDS["hong kong"] } },
    { id: "v2-38", title: "os Dores", publicationYear: 2015, author: { name: "Henrique de senna Fernandes", gender: Gender.MALE }, translator: { name: "Yu Huijuan", gender: Gender.FEMALE }, publisher: "Instituto Cultural de Macau", city: "Macau", originalCity: PT, sourceLanguage: "Portuguese", targetLanguage: "Chinese", customMetadata: { sourceCoord: PT_COORD, targetCoord: COORDS["macau"] } },
    { id: "v2-39", title: "Hoje sinto-Me...", publicationYear: 2015, author: { name: "Madalena Moniz", gender: Gender.FEMALE }, translator: { name: "Gua Gua", gender: Gender.FEMALE }, publisher: "Chongqing Publishing House", city: "Chongqing", originalCity: PT, sourceLanguage: "Portuguese", targetLanguage: "Chinese", customMetadata: { sourceCoord: PT_COORD, targetCoord: COORDS["chongqing"] } },
    { id: "v2-40", title: "A Educação do Estóico", publicationYear: 2015, author: { name: "Fernando Pessoa", gender: Gender.MALE }, translator: { name: "Liu Yongjun", gender: Gender.MALE }, publisher: "China overseas Chinese Press", city: "Beijing", originalCity: PT, sourceLanguage: "Portuguese", targetLanguage: "Chinese", customMetadata: { sourceCoord: PT_COORD, targetCoord: COORDS["beijing"] } },
    { id: "v2-41", title: "o silêncio da água", publicationYear: 2015, author: { name: "José Saramago", gender: Gender.MALE }, translator: { name: "Min Xuefei", gender: Gender.FEMALE }, publisher: "Zhejiang Children's Publishing House", city: "Hangzhou", originalCity: PT, sourceLanguage: "Portuguese", targetLanguage: "Chinese", customMetadata: { sourceCoord: PT_COORD, targetCoord: COORDS["hangzhou"] } },
    { id: "v2-42", title: "A viagem do Elefante", publicationYear: 2015, author: { name: "José Saramago", gender: Gender.MALE }, translator: { name: "Wang Yuan", gender: Gender.FEMALE }, publisher: "Writers Publishing House", city: "Beijing", originalCity: PT, sourceLanguage: "Portuguese", targetLanguage: "Chinese", customMetadata: { sourceCoord: PT_COORD, targetCoord: COORDS["beijing"] } },

    // 2016 Peak
    { id: "v2-43", title: "Nocturno em Macau", publicationYear: 2016, author: { name: "Maria ondina Braga", gender: Gender.FEMALE }, translator: { name: "Wei Ling, Zhu Wenjun", gender: Gender.FEMALE }, publisher: "Instituto Cultural de Macau", city: "Macau", originalCity: PT, sourceLanguage: "Portuguese", targetLanguage: "Chinese", customMetadata: { sourceCoord: PT_COORD, targetCoord: COORDS["macau"] } },
    { id: "v2-44", title: "Lá Fora", publicationYear: 2016, author: { name: "Maria Ana Peixe", gender: Gender.FEMALE }, translator: { name: "Zhang Xiaofei", gender: Gender.FEMALE }, publisher: "Guangxi science and Technology Press", city: "Nanning", originalCity: PT, sourceLanguage: "Portuguese", targetLanguage: "Chinese", customMetadata: { sourceCoord: PT_COORD, targetCoord: COORDS["nanning"] } },
    { id: "v2-45", title: "se Eu Fosse um libro", publicationYear: 2016, author: { name: "José Jorge letria", gender: Gender.MALE }, translator: { name: "Peng Li", gender: Gender.MALE }, publisher: "Trustbridge Publishing limited", city: "Hangzhou", originalCity: PT, sourceLanguage: "Portuguese", targetLanguage: "Chinese", customMetadata: { sourceCoord: PT_COORD, targetCoord: COORDS["hangzhou"] } },
    { id: "v2-46", title: "Daqui Ninguém Passa!", publicationYear: 2016, author: { name: "Isabel Minhós Martins", gender: Gender.FEMALE }, translator: { name: "Huang Hongyan", gender: Gender.FEMALE }, publisher: "Zimu Culture", city: "Taipei", originalCity: PT, sourceLanguage: "Portuguese", targetLanguage: "Chinese", customMetadata: { sourceCoord: PT_COORD, targetCoord: COORDS["taipei"] } },
    { id: "v2-47", title: "O Mundo num segundo", publicationYear: 2016, author: { name: "Isabel Minhós Martins", gender: Gender.FEMALE }, translator: { name: "Sun Shan", gender: Gender.FEMALE }, publisher: "oriental Publishing House", city: "Beijing", originalCity: PT, sourceLanguage: "Portuguese", targetLanguage: "Chinese", customMetadata: { sourceCoord: PT_COORD, targetCoord: COORDS["beijing"] } },
    { id: "v2-48", title: "Andar por aí", publicationYear: 2016, author: { name: "Isabel Minhós Martins", gender: Gender.FEMALE }, translator: { name: "Xu Fangdan", gender: Gender.FEMALE }, publisher: "oriental Publishing House", city: "Beijing", originalCity: PT, sourceLanguage: "Portuguese", targetLanguage: "Chinese", customMetadata: { sourceCoord: PT_COORD, targetCoord: COORDS["beijing"] } },
    { id: "v2-49", title: "libro Clap", publicationYear: 2016, author: { name: "Madalena Matoso", gender: Gender.FEMALE }, translator: { name: "Yu Jiayun", gender: Gender.FEMALE }, publisher: "Nanjing Normal university Press", city: "Nanjing", originalCity: PT, sourceLanguage: "Portuguese", targetLanguage: "Chinese", customMetadata: { sourceCoord: PT_COORD, targetCoord: COORDS["nanjing"] } },
    { id: "v2-50", title: "Clepsidra", publicationYear: 2016, author: { name: "Camilo Pessanha", gender: Gender.MALE }, translator: { name: "Yao Jingming, Jin Guoping", gender: Gender.MALE }, publisher: "Instituto Cultural de Macau", city: "Macau", originalCity: PT, sourceLanguage: "Portuguese", targetLanguage: "Chinese", customMetadata: { sourceCoord: PT_COORD, targetCoord: COORDS["macau"] } },
    { id: "v2-51", title: "Poemas de Fernando Pessoa", publicationYear: 2016, author: { name: "Fernando Pessoa", gender: Gender.MALE }, translator: { name: "ou Fan", gender: Gender.MALE }, publisher: "Shandong literature and Art Co.", city: "Jinan", originalCity: PT, sourceLanguage: "Portuguese", targetLanguage: "Chinese", customMetadata: { sourceCoord: PT_COORD, targetCoord: COORDS["jinan"] } },
    { id: "v2-52", title: "o Meu Avô", publicationYear: 2016, author: { name: "Catarina sobral", gender: Gender.FEMALE }, translator: { name: "Sun Lili", gender: Gender.FEMALE }, publisher: "Jieli Publishing House", city: "Beijing", originalCity: PT, sourceLanguage: "Portuguese", targetLanguage: "Chinese", customMetadata: { sourceCoord: PT_COORD, targetCoord: COORDS["beijing"] } },
    { id: "v2-53", title: "o Bairro", publicationYear: 2016, author: { name: "Gonçalo M. Tavares", gender: Gender.MALE }, translator: { name: "Jin Wenjing", gender: Gender.FEMALE }, publisher: "Shanghai literature and Art Publishing House", city: "Shanghai", originalCity: PT, sourceLanguage: "Portuguese", targetLanguage: "Chinese", customMetadata: { sourceCoord: PT_COORD, targetCoord: COORDS["shanghai"] } },
    { id: "v2-54", title: "o pai mais horrível do mundo", publicationYear: 2016, author: { name: "João Miguel Tavares", gender: Gender.MALE }, translator: { name: "An Guo", gender: Gender.MALE }, publisher: "Changjiang Children's Publishing House", city: "Wuhan", originalCity: PT, sourceLanguage: "Portuguese", targetLanguage: "Chinese", customMetadata: { sourceCoord: PT_COORD, targetCoord: COORDS["wuhan"] } },

    // 2017 Continued Circulation
    { id: "v2-55", title: "Na água Amar o Fogo", publicationYear: 2017, author: { name: "Eugénio de Andrade", gender: Gender.MALE }, translator: { name: "Yao Jingming", gender: Gender.MALE }, publisher: "Hunan literature and Art Publishing House", city: "Changsha", originalCity: PT, sourceLanguage: "Portuguese", targetLanguage: "Chinese", customMetadata: { sourceCoord: PT_COORD, targetCoord: COORDS["changsha"] } },
    { id: "v2-56", title: "Nocturno em Macau", publicationYear: 2017, author: { name: "Maria ondina Braga", gender: Gender.FEMALE }, translator: { name: "Wei Ling, Zhu Wenjun", gender: Gender.FEMALE }, publisher: "People's literature Publishing House", city: "Beijing", originalCity: PT, sourceLanguage: "Portuguese", targetLanguage: "Chinese", customMetadata: { sourceCoord: PT_COORD, targetCoord: COORDS["beijing"] } },
    { id: "v2-57", title: "variação sobre rosas", publicationYear: 2017, author: { name: "Nuno Júdice", gender: Gender.MALE }, translator: { name: "Yao Jingming", gender: Gender.MALE }, publisher: "Chinese university of Hong Kong Press", city: "Hong Kong", originalCity: PT, sourceLanguage: "Portuguese", targetLanguage: "Chinese", customMetadata: { sourceCoord: PT_COORD, targetCoord: COORDS["hong kong"] } },
    { id: "v2-58", title: "versos para os pais lerem aos filhos...", publicationYear: 2017, author: { name: "José Jorge letria", gender: Gender.MALE }, translator: { name: "Zhang Xiaofei", gender: Gender.FEMALE }, publisher: "Zhejiang Children's Publishing House", city: "Hangzhou", originalCity: PT, sourceLanguage: "Portuguese", targetLanguage: "Chinese", customMetadata: { sourceCoord: PT_COORD, targetCoord: COORDS["hangzhou"] } },
    { id: "v2-59", title: "um Ano Inteiro", publicationYear: 2017, author: { name: "Isabel Minhós Martins", gender: Gender.FEMALE }, translator: { name: "Zhang Xiaofei", gender: Gender.FEMALE }, publisher: "Guangxi science and Technology Press", city: "Nanning", originalCity: PT, sourceLanguage: "Portuguese", targetLanguage: "Chinese", customMetadata: { sourceCoord: PT_COORD, targetCoord: COORDS["nanning"] } },
    { id: "v2-60", title: "Este libro está a Chamar-te", publicationYear: 2017, author: { name: "Isabel Minhós Martins", gender: Gender.FEMALE }, translator: { name: "Gong Xiaotu", gender: Gender.MALE }, publisher: "Zhejiang Technology and Business university Press", city: "Hangzhou", originalCity: PT, sourceLanguage: "Portuguese", targetLanguage: "Chinese", customMetadata: { sourceCoord: PT_COORD, targetCoord: COORDS["hangzhou"] } },
    { id: "v2-61", title: "Daqui Ninguém Passa!", publicationYear: 2017, author: { name: "Isabel Minhós Martins", gender: Gender.FEMALE }, translator: { name: "Yuan Shenyi", gender: Gender.FEMALE }, publisher: "Tianjin People's Publishing House", city: "Tianjin", originalCity: PT, sourceLanguage: "Portuguese", targetLanguage: "Chinese", customMetadata: { sourceCoord: PT_COORD, targetCoord: COORDS["tianjin"] } }
];
