
import React, { useState } from 'react';
import { ResearchBlueprint, ResearchDimension } from '../types';
import { generateResearchBlueprint } from '../services/geminiService';

interface TheoryLabProps {
  onClose: () => void;
  onApplyBlueprint: (blueprint: ResearchBlueprint) => void;
}

// Map dimension keys to bilingual labels - vertical format
const DIMENSION_LABELS: Record<string, { en: string, zh: string, icon: string }> = {
  'Agentive (Who)': { en: 'Agentive (Who)', zh: '行动主体维度', icon: '👤' },
  'Textual (What)': { en: 'Textual (What)', zh: '文本特质维度', icon: '📜' },
  'Distributional (Where/When/How)': { en: 'Distributional', zh: '空间流转维度', icon: '📍' },
  'Discursive (Why)': { en: 'Discursive (Why)', zh: '话语建构维度', icon: '💬' },
  'Reception (So what)': { en: 'Reception', zh: '社会接受维度', icon: '🗣️' }
};

// Advanced Offline Logic for TAD Framework
const OFFLINE_KNOWLEDGE_BASE = {
  themes: [
    { keywords: ['gender', 'women', 'feminism', '女性', '性别'], label: 'Sociology of Gender', dhFocus: ['Prosopography', 'SNA'] },
    { keywords: ['poetry', 'verse', 'lyric', '诗歌', '文学', 'poetics'], label: 'Poetics & Style', dhFocus: ['Stylometry', 'Topic Modeling'] },
    { keywords: ['macao', 'colony', 'portugal', '澳门', '葡萄牙', '殖民'], label: 'Colonial Circulation', dhFocus: ['GIS', 'Spatiotemporal Heatmaps'] },
    { keywords: ['history', 'qing', 'republic', '历史', '晚清', '制度'], label: 'Institutional History', dhFocus: ['Institutional Mapping', 'Burt\'s Structural Holes'] },
    { keywords: ['religion', 'jesuit', 'missionary', '宗教', '传教'], label: 'Religious Mediation', dhFocus: ['Network Density', 'Spatio-linguistic clusters'] },
    { keywords: ['science', 'medicine', 'tech', '科学', '技术', '医学'], label: 'Scientific Knowledge Transfer', dhFocus: ['Concept Evolution', 'Parallel Text Analysis'] }
  ],

  getBlueprint: (query: string): ResearchBlueprint => {
    const q = query.toLowerCase();
    const activeTheme = OFFLINE_KNOWLEDGE_BASE.themes.find(t => t.keywords.some(k => q.includes(k))) || { label: 'General Translation Flow', dhFocus: ['Network Analysis', 'GIS'] };
    const keyword = query.split(/\s+/).filter(w => w.length > 2).pop() || "the corpus";

    const questions: Record<string, string[]> = {
      'Agentive (Who)': [
        `How do the professional backgrounds of ${activeTheme.label} mediators influence the circulation of ${keyword}?`,
        `Who are the primary gatekeepers determining which parts of ${keyword} enter the target field?`,
        `Map the power dynamics between patrons and translators in the mediation of ${keyword}.`
      ],
      'Textual (What)': [
        `What lexical shifts occur during the textual migration of ${keyword} across this period?`,
        `How does the target linguistic standard remodel the stylistic features of ${keyword}?`,
        `Measure the stylistic distance between original and translated versions of ${keyword}.`
      ],
      'Distributional (Where/When/How)': [
        `Trace the spatiotemporal trajectory of ${keyword} through key publishing hubs.`,
        `How does the geographic origin of ${keyword} affect its speed of entry into the target market?`,
        `Identify temporal peaks and troughs in the publication volume of ${keyword}.`
      ],
      'Discursive (Why)': [
        `Analyze the paratextual framing used to justify the cultural importation of ${keyword}.`,
        `What ideological transformations are embedded in the prefaces of ${keyword}?`,
        `Mapping the discursive 'Modernity' narratives attached to ${keyword} by mediators.`
      ],
      'Reception (So what)': [
        `Evaluate the long-term canonization of ${keyword} in target academic curriculum.`,
        `How did the initial reception of ${keyword} trigger subsequent re-translations?`,
        `Map the citation networks generated by the critical response to ${keyword}.`
      ]
    };

    const getRandom = (arr: any[]) => arr[Math.floor(Math.random() * arr.length)];

    const dimensions: ResearchDimension[] = Object.keys(questions).map(dimKey => ({
      dimension: dimKey as any,
      coreQuestion: getRandom(questions[dimKey]),
      dataSources: ["National Library Catalogs", "Mediator Biographies", "Publisher Records", "Contemporary Reviews"],
      dhMethods: [getRandom(activeTheme.dhFocus), getRandom(['SNA', 'GIS', 'NLP', 'Quantitative Metrics'])],
      relevance: 85 + Math.floor(Math.random() * 15)
    }));

    return {
      projectScope: `Expert TAD Strategy (${activeTheme.label}): ${query}`,
      dimensions,
      methodology: `Deploying a ${activeTheme.label} lens to investigate the multi-layered circulation of ${keyword} as structured data.`,
      suggestedSchema: [
        { fieldName: "Mediator_Role", description: "Categorization of mediator (e.g. Patron, Translator, Editor)", analyticalUtility: "Socio-professional analysis", importance: "Critical" },
        { fieldName: "Place_of_Mediation", description: "Geographic site where the translation act was finalized", analyticalUtility: "Spatial flow mapping", importance: "Critical" }
      ],
      dataCleaningStrategy: "Resolve publisher aliases and normalize historical geonyms for computational mapping.",
      storageAdvice: "Use a graph database to capture the relational complexities of agents and texts.",
      visualizationStrategy: `Synthesize ${activeTheme.dhFocus[0]} and ${activeTheme.dhFocus[1]} to prove longitudinal shifts.`,
      collectionTips: "Consult paratextual marginalia to identify collaborative mediation efforts."
    };
  }
};

const TheoryLab: React.FC<TheoryLabProps> = ({ onClose, onApplyBlueprint }) => {
  const [query, setQuery] = useState('Gender and Poetry in Late Qing Translation');
  const [isGenerating, setIsGenerating] = useState(false);
  const [blueprint, setBlueprint] = useState<ResearchBlueprint | null>(null);

  const handleGenerate = async () => {
    if (!query.trim()) return;
    setIsGenerating(true);
    
    if (!process.env.API_KEY) {
      await new Promise(r => setTimeout(r, 1200)); 
      setBlueprint(OFFLINE_KNOWLEDGE_BASE.getBlueprint(query));
      setIsGenerating(false);
      return;
    }

    try {
      const bp = await generateResearchBlueprint(query);
      setBlueprint(bp);
    } catch (e) {
      setBlueprint(OFFLINE_KNOWLEDGE_BASE.getBlueprint(query));
    } finally {
      setIsGenerating(false);
    }
  };

  return (
    <div className="fixed inset-0 bg-white z-[900] flex flex-col animate-fadeIn select-none overflow-hidden font-sans">
      <header className="px-12 py-8 flex items-center justify-between border-b border-slate-100 bg-white shrink-0">
        <div className="flex items-center gap-6">
          <button 
            onClick={onClose}
            className="w-12 h-12 bg-slate-100 hover:bg-indigo-100 rounded-xl flex items-center justify-center text-slate-400 text-xl transition-all shadow-sm"
            title="Return Home / 返回首页"
          >
            🏠
          </button>
          <div className="w-12 h-12 bg-emerald-600 rounded-2xl flex items-center justify-center text-white text-2xl shadow-xl shadow-emerald-200">🔬</div>
          <div className="space-y-0.5">
            <h1 className="text-3xl font-bold text-slate-900 serif leading-none">Methodology Lab</h1>
            <h1 className="text-xl font-bold text-slate-500 serif leading-none">研究方法室</h1>
            <p className="text-[10px] font-black text-slate-400 uppercase tracking-widest pt-1">Translation as Data (TAD) Framework / 翻译即数据研究框架</p>
          </div>
        </div>
        <div className="flex items-center gap-6">
          <div className={`px-5 py-2 rounded-full flex items-center gap-2 border ${process.env.API_KEY ? 'bg-indigo-50 border-indigo-100' : 'bg-amber-50 border-amber-100'}`}>
            <span className={`w-2 h-2 rounded-full animate-pulse ${process.env.API_KEY ? 'bg-indigo-500' : 'bg-amber-500'}`}></span>
            <span className={`text-[10px] font-black uppercase tracking-widest ${process.env.API_KEY ? 'text-indigo-700' : 'text-amber-700'}`}>
                {process.env.API_KEY ? 'AI Logic Active' : 'Expert Framework Logic (Heuristic Offline)'}
            </span>
          </div>
          <button onClick={onClose} className="text-5xl text-slate-200 hover:text-slate-900 transition-colors leading-none">&times;</button>
        </div>
      </header>

      <main className="flex-1 overflow-y-auto bg-slate-50/20 px-12 py-10 space-y-12 custom-scrollbar">
        <div className="max-w-[1400px] mx-auto bg-white rounded-[2.5rem] p-12 shadow-sm border border-slate-200 flex flex-col gap-10">
          <div className="space-y-4 text-left">
            <label className="block">
              <span className="text-[11px] font-black uppercase text-slate-900 tracking-widest block">Research Inquiry</span>
              <span className="text-[10px] font-bold text-slate-400 block">翻译研究课题</span>
            </label>
            <textarea 
              value={query}
              onChange={(e) => setQuery(e.target.value)}
              className="w-full h-32 bg-slate-50 border border-slate-100 rounded-[2rem] p-8 text-2xl font-serif italic text-slate-800 outline-none focus:ring-8 ring-indigo-50 transition-all resize-none shadow-inner"
              placeholder="e.g., 'Retranslation of Camões in 20th Century China'..."
            />
          </div>
          <div className="flex justify-between items-center">
            <div className="space-y-1">
              <p className="text-[11px] text-slate-600 font-serif italic max-w-2xl leading-relaxed">
                  输入您的研究课题，系统将应用 **Translation as Data (TAD)** 框架。
              </p>
              <p className="text-[11px] text-slate-400 font-serif italic max-w-2xl leading-relaxed">
                  Enter your topic, and the system will apply the TAD framework to map dimensions like Agentive, Textual, and Flow.
              </p>
            </div>
            <div className="flex gap-4">
                <button 
                  onClick={onClose}
                  className="px-8 py-6 bg-slate-100 hover:bg-slate-200 text-slate-400 rounded-2xl text-[12px] font-black uppercase tracking-widest transition-all"
                >
                    <span className="block">Cancel</span>
                    <span className="block opacity-60">返回主页</span>
                </button>
                <button 
                  onClick={handleGenerate}
                  disabled={isGenerating || !query.trim()}
                  className="px-12 py-6 bg-slate-900 hover:bg-emerald-600 disabled:bg-slate-300 text-white rounded-2xl text-[12px] font-black uppercase tracking-widest transition-all shadow-2xl active:scale-95 flex flex-col items-center justify-center px-16"
                >
                  {isGenerating ? 'ANALYZING...' : (
                    <>
                      <span className="block">PLAN TAD STRATEGY</span>
                      <span className="block text-[10px] opacity-60">规划研究路径 →</span>
                    </>
                  )}
                </button>
            </div>
          </div>
        </div>

        {(blueprint || isGenerating) && (
          <div className="max-w-[1400px] mx-auto space-y-10 animate-slideUp pb-32">
            <div className="flex items-center gap-6">
               <div className="h-px bg-slate-200 flex-1"></div>
               <h3 className="text-[11px] font-black uppercase text-slate-400 tracking-[0.6em] whitespace-nowrap">TAD Matrix Strategy Board</h3>
               <div className="h-px bg-slate-200 flex-1"></div>
            </div>

            {isGenerating ? (
               <div className="bg-white rounded-[4rem] p-32 border border-slate-200 flex flex-col items-center justify-center gap-8 shadow-sm">
                  <div className="w-16 h-16 border-4 border-slate-100 border-t-emerald-500 rounded-full animate-spin"></div>
                  <p className="text-2xl font-serif italic text-slate-400">Constructing Dynamic Research Matrix...</p>
               </div>
            ) : (
              <div className="space-y-6">
                {blueprint?.dimensions.map((dim, idx) => {
                  const label = DIMENSION_LABELS[dim.dimension] || { en: dim.dimension, zh: '未知维度', icon: '❓' };
                  return (
                    <div key={idx} className="bg-white rounded-3xl border border-slate-200 flex items-stretch overflow-hidden hover:shadow-2xl transition-all border-l-8 border-l-transparent hover:border-l-emerald-500 group">
                      <div className="w-64 bg-slate-50/50 flex flex-col items-center justify-center p-10 shrink-0 border-r border-slate-100 group-hover:bg-slate-50 transition-colors">
                          <div className="text-4xl mb-4 bg-white w-20 h-20 rounded-3xl flex items-center justify-center shadow-inner border border-slate-50">{label.icon}</div>
                          <h4 className="text-xl font-bold text-slate-800 serif text-center leading-tight">{label.zh}</h4>
                          <span className="text-[10px] font-black text-slate-300 uppercase tracking-widest mt-2">{label.en}</span>
                      </div>

                      <div className="flex-1 p-12 grid grid-cols-1 lg:col-span-12 gap-16 items-start md:grid-cols-3">
                          <div className="space-y-5">
                              <h5 className="text-[11px] font-black uppercase text-emerald-600 tracking-widest">Key Question / 核心问题</h5>
                              <p className="text-2xl font-serif font-semibold text-slate-900 leading-snug tracking-tight">{dim.coreQuestion}</p>
                          </div>
                          
                          <div className="space-y-5">
                              <h5 className="text-[11px] font-black uppercase text-slate-400 tracking-widest">Archival Sources / 档案来源</h5>
                              <div className="flex flex-wrap gap-3">
                                  {dim.dataSources.map(s => <span key={s} className="px-5 py-2.5 bg-slate-100 text-[11px] font-bold text-slate-500 rounded-xl border border-slate-200/40">{s}</span>)}
                              </div>
                          </div>

                          <div className="space-y-5">
                              <h5 className="text-[11px] font-black uppercase text-slate-400 tracking-widest">DH Methods / 计算方法</h5>
                              <div className="flex flex-wrap gap-3">
                                  {dim.dhMethods.map(m => <span key={m} className="px-5 py-2.5 bg-slate-900 text-[10px] font-black uppercase text-white rounded-xl tracking-tighter shadow-lg shadow-slate-200">{m}</span>)}
                              </div>
                          </div>
                      </div>
                    </div>
                  );
                })}

                <div className="mt-24 p-20 bg-white rounded-[4.5rem] border border-slate-200 shadow-sm space-y-16">
                   <div className="text-center space-y-4">
                      <h5 className="text-[12px] font-black uppercase text-emerald-600 tracking-[0.5em]">TAD Synthesis / 综合研究蓝图</h5>
                      <h2 className="text-6xl font-bold text-slate-900 serif leading-tight max-w-5xl mx-auto italic tracking-tight">
                        "{blueprint?.methodology}"
                      </h2>
                   </div>

                   <div className="grid grid-cols-1 md:grid-cols-2 gap-24 border-t border-slate-100 pt-20">
                      <div className="space-y-8">
                        <h6 className="text-[11px] font-black uppercase text-slate-400 tracking-widest flex items-center gap-4">
                          <div className="w-3 h-3 rounded-full bg-indigo-500"></div> Visual Evidence Plan / 可视化论证
                        </h6>
                        <p className="text-2xl font-serif text-slate-600 leading-relaxed italic border-l-4 border-slate-100 pl-10">
                          {blueprint?.visualizationStrategy}
                        </p>
                      </div>
                      <div className="space-y-8">
                        <h6 className="text-[11px] font-black uppercase text-slate-400 tracking-widest flex items-center gap-4">
                          <div className="w-3 h-3 rounded-full bg-emerald-500"></div> Archival Strategy / 档案策略
                        </h6>
                        <p className="text-2xl font-serif text-slate-600 leading-relaxed italic border-l-4 border-slate-100 pl-10">
                          {blueprint?.dataCleaningStrategy}
                        </p>
                      </div>
                   </div>
                </div>

                <div className="flex justify-center pt-24 pb-20">
                    <button 
                      onClick={() => blueprint && onApplyBlueprint(blueprint)}
                      className="px-24 py-10 bg-slate-900 text-white rounded-[3.5rem] font-bold text-sm uppercase tracking-[0.5em] hover:bg-emerald-600 transition-all shadow-2xl hover:scale-105 active:scale-95 ring-[12px] ring-emerald-50 flex flex-col items-center"
                    >
                        <span className="block">Apply TAD Framework</span>
                        <span className="block opacity-60">部署研究蓝图 →</span>
                    </button>
                </div>
              </div>
            )}
          </div>
        )}
      </main>
    </div>
  );
};

export default TheoryLab;
